apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: "2022-07-21T18:41:22Z"
  name: secretgen-controller.carvel.dev
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - config/package-bundle/config
              - config/release
          - kbld:
              paths:
              - '-'
              - config/release
      export:
      - imgpkgBundle:
          image: ysethiya/secretgen-controller2
          useKbldImagesLock: true
        includePaths:
        - config/package-bundle/config
        - config/release
