#@data/values-schema
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults
#@schema/desc "Configuration explicity for developing secretgen-controller"
dev:
  #@schema/desc "Location of secretgen-controller image"
  image_repo:  docker.io/ysethiya/sgc
  #@schema/desc "Development version"
  version: develop