#release.yml
name: sgc-release

on:
  push:
    tags:
      - "v*"

jobs:
  sgcreleaser:
    name: secretgen controller release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Install Carvel Tools
        uses: vmware-tanzu/carvel-setup-action@v1

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GH_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Setting up minikube
        run: |
          set -e -x
          minikube start --driver=docker --wait=all
          docker buildx create minikube --use --driver=kubernetes --bootstrap

      - name: Fetch kctrl
        uses: actions/checkout@v3
        with:
          ref: develop
          repository: vmware-tanzu/carvel-kapp-controller
          path: carvel-kapp-controller
          fetch-depth: 0

      - name: Build kctrl
        working-directory: ./carvel-kapp-controller/cli
        run: |
          ./hack/build.sh
      
      # - name: Set Versions
      #   uses: actions/github-script@v4
      #   id: set_version
      #   with:
      #     script: |
      #       const tag = context.ref.substring(10)
      #       const no_v = tag.replace('v', '')
      #       core.setOutput('no-v', no_v)

      - name: Run Package build
        run: |
          ./carvel-kapp-controller/cli/kctrl pkg release -y -v ${{constraintVersion:1}} --debug

      - name: Check Package and Metadata file generated
        run: |
          ls -la carvel-artifacts/packages/secretgen-controller.carvel.dev
      
      - name: Create draft release with package and metadata
        uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            carvel-artifacts/packages/secretgen-controller.carvel.dev/metadata.yml
            carvel-artifacts/packages/secretgen-controller.carvel.dev/package.yml
          draft: true
      - name: Run PackageCR Validation Tests
        run: |
          set -e -x

          # deploy admin sa for secretgen-controller - enough permissions for SGC to be deployed properly
          kapp deploy -a rbac -f https://raw.githubusercontent.com/vmware-tanzu/carvel-kapp-controller/develop/examples/rbac/cluster-admin.yml -y

          # Kapp-controller is needed for our PackageInstall
          kapp deploy -a kc -f https://github.com/vmware-tanzu/carvel-kapp-controller/releases/latest/download/release.yml -y

          constraintVersion="${{ github.ref_name }}"
          cat << EOF > pkgi.yml
          ---
          apiVersion: packaging.carvel.dev/v1alpha1
          kind: PackageInstall
          metadata:
            name: secretgen-controller
          spec:
            serviceAccountName: cluster-admin-sa
            packageRef:
              refName: secretgen-controller.carvel.dev
              apiVersion: packaging.carvel.dev/v1alpha1
              versionSelection:
                constraints: "${constraintVersion:1}"
          EOF

          cat pkgi.yml

          kapp deploy -a sg -f carvel-artifacts/packages/secretgen-controller.carvel.dev/package.yml -f carvel-artifacts/packages/secretgen-controller.carvel.dev/metadata.yml -f pkgi.yml -y

          export SECRETGEN_E2E_NAMESPACE=secretgen-test

          ./hack/test-e2e.sh