name: sgc-release

on:
  push:
    tags:
      - "v*"

jobs:
  sgcreleaser:
    name: secretgen controller release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Install Carvel Tools
        run: |
          curl -L https://carvel.dev/install.sh | bash

      - name: Fetch kctrl
        uses: actions/checkout@v3
        with:
          ref: pkg-authoring
          repository: vmware-tanzu/carvel-kapp-controller
          path: carvel-kapp-controller
          fetch-depth: 0

      - name: Build kctrl
        working-directory: ./carvel-kapp-controller/cli
        run: |
          ./hack/build.sh

      - name: Run Package build
        run: |
          ./carvel-kapp-controller/cli/kctrl pkg build create -y -v 1.0.0
            






          
